spring.application.name=socialnetwork

front.base.url=http://localhost:8080

spring.datasource.url=jdbc:mariadb://178.33.122.21:3306/hangardb_akse63476
spring.datasource.username=akse63476
spring.datasource.password=pf8kN1ewa66jwRm3YeVeE2f6
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false